### ISSUE TITLE
error on startup of docker containers

### ISSUE THREAD

**Issue by Z1mDMan** [crocofied/CoreControl#1]
Copy/pasted the compose yaml into dockge and deployed the containers and I keep getting the following in the logs:

agent-1  | Error fetching applications: failed to connect to `host=db user=postgres database=postgres`: tls error (server refused TLS connection)

I just left everything the defaults in the compose yaml and intend on configuring the login credentials etc. once I know it works. Let me know if you need anything else from me on this.

Excited to see this in action!

**Comment by baxterblk** [comment]
When attempting to install CoreControl-0.0.1.tar.gz using the provided docker-compose.yml configuration, two key issues were encountered:

TLS Connection Errors: The agent service repeatedly failed with Error fetching applications: failed to connect to host=db user=postgres database=postgres: tls error (server refused TLS connection)
Missing Next.js Build: The web service failed with [Error: Could not find a production build in the '.next' directory. Try building your app with 'next build' before starting the production server]
Solution
Modified the docker-compose.yml to address both issues:

Fixed TLS Error: Removed sslmode=require from the DATABASE_URL parameters and added TLS_MODE: "disable" to the agent service
Fixed Build Issue: Changed from using pre-built Docker images to building from source using the included Dockerfiles

**Comment by Z1mDMan** [comment]
> When attempting to install CoreControl-0.0.1.tar.gz using the provided docker-compose.yml configuration, two key issues were encountered:
> 
> TLS Connection Errors: The agent service repeatedly failed with Error fetching applications: failed to connect to host=db user=postgres database=postgres: tls error (server refused TLS connection) Missing Next.js Build: The web service failed with [Error: Could not find a production build in the '.next' directory. Try building your app with 'next build' before starting the production server] Solution Modified the docker-compose.yml to address both issues:
> 
> Fixed TLS Error: Removed sslmode=require from the DATABASE_URL parameters and added TLS_MODE: "disable" to the agent service Fixed Build Issue: Changed from using pre-built Docker images to building from source using the included Dockerfiles

good info. Tried just modifying the compose file and still having issues.

web-1    | [Error: Could not find a production build in the '.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id]
web-1 exited with code 1
db-1     | 2025-04-14 02:24:33.958 UTC [53] FATAL:  unrecognized configuration parameter "schema"
agent-1  | Error fetching applications: failed to connect to `host=db user=postgres database=postgres`: server error (FATAL: unrecognized configuration parameter "schema" (SQLSTATE 42704))
db-1     | 2025-04-14 02:24:38.958 UTC [55] FATAL:  unrecognized configuration parameter "schema"
agent-1  | Error fetching applications: failed to connect to `host=db user=postgres database=postgres`: server error (FATAL: unrecognized configuration parameter "schema" (SQLSTATE 42704))
db-1     | 2025-04-14 02:24:43.960 UTC [58] FATAL:  unrecognized configuration parameter "schema"
agent-1  | Error fetching applications: failed to connect to `host=db user=postgres database=postgres`: server error (FATAL: unrecognized configuration parameter "schema" (SQLSTATE 42704))
db-1     | 2025-04-14 02:24:48.960 UTC [60] FATAL:  unrecognized configuration parameter "schema"
agent-1  | Error fetching applications: failed to connect to `host=db user=postgres database=postgres`: server error (FATAL: unrecognized configuration parameter "schema" (SQLSTATE 42704))
db-1     | 2025-04-14 02:24:53.960 UTC [62] FATAL:  unrecognized configuration parameter "schema"
agent-1  | Error fetching applications: failed to connect to `host=db user=postgres database=postgres`: server error (FATAL: unrecognized configuration parameter "schema" (SQLSTATE 42704))
db-1     | 2025-04-14 02:24:58.958 UTC [64] FATAL:  unrecognized configuration parameter "schema"
agent-1  | Error fetching applications: failed to connect to `host=db user=postgres database=postgres`: server error (FATAL: unrecognized configuration parameter "schema" (SQLSTATE 42704))
db-1     | 2025-04-14 02:25:03.961 UTC [66] FATAL:  unrecognized configuration parameter "schema"
agent-1  | Error fetching applications: failed to connect to `host=db user=postgres database=postgres`: server error (FATAL: unrecognized configuration parameter "schema" (SQLSTATE 42704))
db-1     | 2025-04-14 02:25:08.960 UTC [68] FATAL:  unrecognized configuration parameter "schema"
agent-1  | Error fetching applications: failed to connect to `host=db user=postgres database=postgres`: server error (FATAL: unrecognized configuration parameter "schema" (SQLSTATE 42704))
db-1     | 2025-04-14 02:25:13.959 UTC [71] FATAL:  unrecognized configuration parameter "schema"
agent-1  | Error fetching applications: failed to connect to `host=db user=postgres database=postgres`: server error (FATAL: unrecognized configuration parameter "schema" (SQLSTATE 42704))
db-1     | 2025-04-14 02:25:18.955 UTC [73] FATAL:  unrecognized configuration parameter "schema"
agent-1  | Error fetching applications: failed to connect to `host=db user=postgres database=postgres`: server error (FATAL: unrecognized configuration parameter "schema" (SQLSTATE 42704))
db-1     | 2025-04-14 02:25:23.960 UTC [75] FATAL:  unrecognized configuration parameter "schema"
agent-1  | Error fetching applications: failed to connect to `host=db user=postgres database=postgres`: server error (FATAL: unrecognized configuration parameter "schema" (SQLSTATE 42704))
db-1     | 2025-04-14 02:25:28.961 UTC [77] FATAL:  unrecognized configuration parameter "schema"
agent-1  | Error fetching applications: failed to connect to `host=db user=postgres database=postgres`: server error (FATAL: unrecognized configuration parameter "schema" (SQLSTATE 42704))
db-1     | 2025-04-14 02:25:33.953 UTC [79] FATAL:  unrecognized configuration parameter "schema"
agent-1  | Error fetching applications: failed to connect to `host=db user=postgres database=postgres`: server error (FATAL: unrecognized configuration parameter "schema" (SQLSTATE 42704))
agent-1  | Error fetching applications: failed to connect to `host=db user=postgres database=postgres`: server error (FATAL: unrecognized configuration parameter "schema" (SQLSTATE 42704))
db-1     | 2025-04-14 02:25:38.960 UTC [81] FATAL:  unrecognized configuration parameter "schema"
db-1     | 2025-04-14 02:25:43.960 UTC [84] FATAL:  unrecognized configuration parameter "schema"
agent-1  | Error fetching applications: failed to connect to `host=db user=postgres database=postgres`: server error (FATAL: unrecognized configuration parameter "schema" (SQLSTATE 42704))
db-1     | 2025-04-14 02:25:48.961 UTC [86] FATAL:  unrecognized configuration parameter "schema"
agent-1  | Error fetching applications: failed to connect to `host=db user=postgres database=postgres`: server error (FATAL: unrecognized configuration parameter "schema" (SQLSTATE 42704))
agent-1  | Error fetching applications: failed to connect to `host=db user=postgres database=postgres`: server error (FATAL: unrecognized configuration parameter "schema" (SQLSTATE 42704))
db-1     | 2025-04-14 02:25:53.960 UTC [88] FATAL:  unrecognized configuration parameter "schema"
db-1     | 2025-04-14 02:25:58.960 UTC [90] FATAL:  unrecognized configuration parameter "schema"
agent-1  | Error fetching applications: failed to connect to `host=db user=postgres database=postgres`: server error (FATAL: unrecognized configuration parameter "schema" (SQLSTATE 42704))
db-1     | 2025-04-14 02:26:03.960 UTC [92] FATAL:  unrecognized configuration parameter "schema"
agent-1  | Error fetching applications: failed to connect to `host=db user=postgres database=postgres`: server error (FATAL: unrecognized configuration parameter "schema" (SQLSTATE 42704))

**Comment by Z1mDMan** [comment]
using the following with the mentioned changes:

services:
  web:
    image: haedlessdev/corecontrol:latest
    ports:
      - 3000:3000
    environment:
      LOGIN_EMAIL: mail@example.com
      LOGIN_PASSWORD: SecretPassword
      JWT_SECRET: RANDOM_SECRET
      ACCOUNT_SECRET: RANDOM_SECRET
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
      - agent
  agent:
    image: haedlessdev/corecontrol-agent:latest
    environment:
      TLS_MODE: disable
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: null

I am now getting this:

web-1    |  ✓ Starting...
web-1    | [Error: Could not find a production build in the '.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id]
web-1 exited with code 1
agent-1  | Error fetching applications: ERROR: relation "application" does not exist (SQLSTATE 42P01)
db-1     | 2025-04-14 12:05:34.749 UTC [34] ERROR:  relation "application" does not exist at character 55
db-1     | 2025-04-14 12:05:34.749 UTC [34] STATEMENT:  
db-1     |              SELECT id, "publicURL", online 
db-1     |              FROM application 
db-1     |              WHERE "publicURL" IS NOT NULL
db-1     |          
db-1     | 2025-04-14 12:05:39.734 UTC [34] ERROR:  relation "application" does not exist at character 55
db-1     | 2025-04-14 12:05:39.734 UTC [34] STATEMENT:  
db-1     |              SELECT id, "publicURL", online 
db-1     |              FROM application 
db-1     |              WHERE "publicURL" IS NOT NULL
db-1     |          
agent-1  | Error fetching applications: ERROR: relation "application" does not exist (SQLSTATE 42P01)
db-1     | 2025-04-14 12:05:44.730 UTC [34] ERROR:  relation "application" does not exist at character 55
agent-1  | Error fetching applications: ERROR: relation "application" does not exist (SQLSTATE 42P01)
db-1     | 2025-04-14 12:05:44.730 UTC [34] STATEMENT:  
db-1     |              SELECT id, "publicURL", online 
db-1     |              FROM application 
db-1     |              WHERE "publicURL" IS NOT NULL
db-1     |          
db-1     | 2025-04-14 12:05:49.735 UTC [34] ERROR:  relation "application" does not exist at character 55
db-1     | 2025-04-14 12:05:49.735 UTC [34] STATEMENT:  
db-1     |              SELECT id, "publicURL", online 
db-1     |              FROM application 
db-1     |              WHERE "publicURL" IS NOT NULL
db-1     |          
agent-1  | Error fetching applications: ERROR: relation "application" does not exist (SQLSTATE 42P01)
agent-1  | Error fetching applications: ERROR: relation "application" does not exist (SQLSTATE 42P01)
db-1     | 2025-04-14 12:05:54.730 UTC [34] ERROR:  relation "application" does not exist at character 55
db-1     | 2025-04-14 12:05:54.730 UTC [34] STATEMENT:  
db-1     |              SELECT id, "publicURL", online 
db-1     |              FROM application 
db-1     |              WHERE "publicURL" IS NOT NULL
db-1     |          
agent-1  | Error fetching applications: ERROR: relation "application" does not exist (SQLSTATE 42P01)
db-1     | 2025-04-14 12:05:59.734 UTC [34] ERROR:  relation "application" does not exist at character 55
db-1     | 2025-04-14 12:05:59.734 UTC [34] STATEMENT:  
db-1     |              SELECT id, "publicURL", online 
db-1     |              FROM application 
db-1     |              WHERE "publicURL" IS NOT NULL
db-1     |          
db-1     | 2025-04-14 12:06:04.734 UTC [34] ERROR:  relation "application" does not exist at character 55
agent-1  | Error fetching applications: ERROR: relation "application" does not exist (SQLSTATE 42P01)
db-1     | 2025-04-14 12:06:04.734 UTC [34] STATEMENT:  
db-1     |              SELECT id, "publicURL", online 
db-1     |              FROM application 
db-1     |              WHERE "publicURL" IS NOT NULL
db-1     |          
agent-1  | Error fetching applications: ERROR: relation "application" does not exist (SQLSTATE 42P01)
db-1     | 2025-04-14 12:06:09.734 UTC [34] ERROR:  relation "application" does not exist at character 55
db-1     | 2025-04-14 12:06:09.734 UTC [34] STATEMENT:  
db-1     |              SELECT id, "publicURL", online 
db-1     |              FROM application 
db-1     |              WHERE "publicURL" IS NOT NULL
db-1     |          
agent-1  | Error fetching applications: ERROR: relation "application" does not exist (SQLSTATE 42P01)
db-1     | 2025-04-14 12:06:14.734 UTC [34] ERROR:  relation "application" does not exist at character 55
db-1     | 2025-04-14 12:06:14.734 UTC [34] STATEMENT:  
db-1     |              SELECT id, "publicURL", online 
db-1     |              FROM application 
db-1     |              WHERE "publicURL" IS NOT NULL
db-1     |          
db-1     | 2025-04-14 12:06:19.730 UTC [34] ERROR:  relation "application" does not exist at character 55
db-1     | 2025-04-14 12:06:19.730 UTC [34] STATEMENT:  
agent-1  | Error fetching applications: ERROR: relation "application" does not exist (SQLSTATE 42P01)
db-1     |              SELECT id, "publicURL", online 
db-1     |              FROM application 
db-1     |              WHERE "publicURL" IS NOT NULL
db-1     |          
agent-1  | Error fetching applications: ERROR: relation "application" does not exist (SQLSTATE 42P01)
db-1     | 2025-04-14 12:06:24.734 UTC [34] ERROR:  relation "application" does not exist at character 55
db-1     | 2025-04-14 12:06:24.734 UTC [34] STATEMENT:  
db-1     |              SELECT id, "publicURL", online 
db-1     |              FROM application 
db-1     |              WHERE "publicURL" IS NOT NULL
db-1     |          
agent-1  | Error fetching applications: ERROR: relation "application" does not exist (SQLSTATE 42P01)
db-1     | 2025-04-14 12:06:29.734 UTC [34] ERROR:  relation "application" does not exist at character 55
db-1     | 2025-04-14 12:06:29.734 UTC [34] STATEMENT:  
db-1     |              SELECT id, "publicURL", online 
db-1     |              FROM application 
db-1     |              WHERE "publicURL" IS NOT NULL
db-1     |          


thanks!

**Comment by xxcbzxx** [comment]
rror: Could not find a production build in the '.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id]

> corecontrol@0.1.0 start


> next start

   ▲ Next.js 15.3.0

   - Local:        http://localhost:3000

   - Network:      http://10.0.8.184:3000

 ✓ Starting...

[Error: Could not find a production build in the '.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id]

im getting flooded with this.

**Comment by crocofied** [comment]
Hey @xxcbzxx @Z1mDMan 

I just pushed v0.0.3 with a hotfix. Can you try to repull and restart the application?

**Comment by kuartelgeneral** [comment]
> Hey [@xxcbzxx](https://github.com/xxcbzxx) [@Z1mDMan](https://github.com/Z1mDMan)
> 
> I just pushed v0.0.3 with a hotfix. Can you try to repull and restart the application?

Thanks, its working now for me with Portainer 👍

**Comment by Z1mDMan** [comment]
> Hey [@xxcbzxx](https://github.com/xxcbzxx) [@Z1mDMan](https://github.com/Z1mDMan)
> 
> I just pushed v0.0.3 with a hotfix. Can you try to repull and restart the application?

That resolved my issues. Thank you!

**Comment by crocofied** [comment]
Great, will close the issue now!
